services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/usr/app/back
    image: nina/backend
    networks:
      - nina-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/app/front
    image: nina/frontend
    networks:
      - nina-network
    
networks:
  nina-network:
